name: vps-config

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/http.d:/etc/nginx/http.d
      - ../nginx/mime.types:/etc/nginx/mime.types
      - ../nginx/common-headers.conf:/etc/nginx/common-headers.conf
    networks:
      - vps-network
    depends_on:
      - app
      - app2
  app:
    container_name: hello-app1
    image: brendosp/hello-java:latest
    restart: on-failure
    networks:
      - vps-network
  app2:
    container_name: hello-app2
    image: brendosp/hello-java:latest
    restart: on-failure
    networks:
      - vps-network
  app3:
    container_name: hello-app3
    image: brendosp/hello-java:latest
    restart: on-failure
    networks:
      - vps-network

networks:
  vps-network:
      driver: bridge